### ISSUE TITLE
Passing `true` to options object doesn't compress

### ISSUE THREAD

**Issue by vbersier** [NikolaRHristov/astro-compress#27]
Passing `true` to a key for the configuration object doesn't actually perform compression for that item, and is considered the same as `false`. Either change the type description to reflect that only a configuration object or `false` can be passed, or accept `true` as argument to use the defaults.

Example:

```ts
import { defineConfig } from 'astro/config'
import compress from 'astro-compress'

// https://astro.build/config
export default defineConfig({
	integrations: [
		compress({
			css: false,
			html: true, // note `true` is passed here
			js: false,
			img: false,
			svg: false
		})
	]
})
```

This doesn't result in the HTML being compressed, and it not flagged as invalid by typescript, because the type definition goes:

```ts
export interface Options {
    [key: string]: any;
    /**
     * Astro build path.
     * @default "./dist/"
     */
    path?: string;
   // abbreviated
    /**
     * [html-minifier-terser] options.
     */
    html?: boolean | HTML; // should be `false | HTML` if this is the inteded behavior
   // abbreviated
}
```

**Comment by NikolaRHristov** [comment]
`true` is a valid option call in this case. It just doesn't pass the full option object to the html-minifier-terser library. The options you have in https://github.com/NikolaRHristov/astro-compress/blob/main/src/options/index.ts#L56-L95 are opinionated and you can just pass `true`. Check https://github.com/terser/html-minifier-terser for more info.

**Comment by beeb** [comment]
> `true` is a valid option call in this case. It just doesn't pass the full option object to the html-minifier-terser library. The options you have in https://github.com/NikolaRHristov/astro-compress/blob/main/src/options/index.ts#L56-L95 are opinionated and you can just pass `true`. Check https://github.com/terser/html-minifier-terser for more info.

I have observed that when I pass true, the HTML is not minified. Is this expected behavior?

**Comment by vbersier** [comment]
> `true` is a valid option call in this case. It just doesn't pass the full option object to the html-minifier-terser library. The options you have in https://github.com/NikolaRHristov/astro-compress/blob/main/src/options/index.ts#L56-L95 are opinionated and you can just pass `true`. Check https://github.com/terser/html-minifier-terser for more info.

Passing `true` doesn't minify the HTML. Is this expected behavior?

**Comment by beeb** [comment]
OK I will need to investigate further because it didn't process the file at all in my case

**Comment by vbersier** [comment]
OK I will need to investigate further because it didn't process the file at all in my case

**Comment by vbersier** [comment]
@NikolaRHristov Here is my repro: https://github.com/vbersier/astro-compress-repro

**Comment by NikolaRHristov** [comment]
I'll take a look later today, thank you!

**Comment by NikolaRHristov** [comment]
Since we do not want to limit the behavior of the options object by only setting `false` or the correct option type from TypeScript, I have made it so that when you use `true` the default options object will be used for each option value. Thank you for this enhancement!

**Comment by NikolaRHristov** [comment]
Can I add you as a Co-Author?

**Comment by beeb** [comment]
> Can I add you as a Co-Author?

Sure thing! Thanks for the fix

**Comment by vbersier** [comment]
> Can I add you as a Co-Author?

Sure thing! Thanks for the fix

**Comment by vbersier** [comment]
Btw I'm in the process of migrating everything to my alt account https://github.com/beeb so this account (vbersier) will cease to exist soon.

**Comment by NikolaRHristov** [comment]
Alright.
